
//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

#include <windows.h>
#include <ppltasks.h>
#include <concrt.h>
#include <collection.h>
#include <windows.devices.alljoyn.interop.h>
#include <map>

#include <alljoyn_c/busattachment.h>
#include <alljoyn_c/dbusstddefines.h>
#include <alljoyn_c/AboutData.h>
#include <alljoyn_c/AboutObj.h>
#include <alljoyn_c/AboutObjectDescription.h>

#include "AllJoynHelpers.h"
#include "AllJoynBusObjectManager.h"

#define PROJECT_NAMESPACE net::allplay
#include "Structures.h"
#include "MediaPlayer/MediaPlayerStructures.h"
#include "Volume/VolumeStructures.h"
#include "TypeConversionHelpers.h"

// MediaPlayer
#include "MediaPlayer/MediaPlayerMethodResults.h"
#include "MediaPlayer/MediaPlayerEventArgs.h"
#include "MediaPlayer/IMediaPlayerService.h"
#include "MediaPlayer/MediaPlayerSignals.h"
#include "MediaPlayer/MediaPlayerProducer.h"
#include "MediaPlayer/MediaPlayerWatcher.h"
#include "MediaPlayer/MediaPlayerConsumer.h"
#include "MediaPlayer/MediaPlayerServiceEventArgs.h"
#include "MediaPlayer/MediaPlayerServiceEventAdapter.h"

//ZoneManager
#include "ZoneManager/ZoneManagerMethodResults.h"
#include "ZoneManager/ZoneManagerEventArgs.h"
#include "ZoneManager/IZoneManagerService.h"
#include "ZoneManager/ZoneManagerSignals.h"
#include "ZoneManager/ZoneManagerProducer.h"
#include "ZoneManager/ZoneManagerWatcher.h"
#include "ZoneManager/ZoneManagerConsumer.h"
#include "ZoneManager/ZoneManagerServiceEventArgs.h"
#include "ZoneManager/ZoneManagerServiceEventAdapter.h"

//MCU
#include "MCU/MCUMethodResults.h"
#include "MCU/MCUEventArgs.h"
#include "MCU/IMCUService.h"
#include "MCU/MCUSignals.h"
#include "MCU/MCUProducer.h"
#include "MCU/MCUWatcher.h"
#include "MCU/MCUConsumer.h"
#include "MCU/MCUServiceEventArgs.h"
#include "MCU/MCUServiceEventAdapter.h"

//Volume
#include "Volume/VolumeMethodResults.h"
#include "Volume/VolumeEventArgs.h"
#include "Volume/IVolumeService.h"
#include "Volume/VolumeSignals.h"
#include "Volume/VolumeProducer.h"
#include "Volume/VolumeWatcher.h"
#include "Volume/VolumeConsumer.h"
#include "Volume/VolumeServiceEventArgs.h"
#include "Volume/VolumeServiceEventAdapter.h"

#include "AllPlayProducer.h"